// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Marketing.Migrations.Promotion
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SerializedRewards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SerializedRewards));
        
        string IMigrationMetadata.Id
        {
            get { return "201504021220218_SerializedRewards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
