// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Marketing.Migrations.Content
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PropertyValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropertyValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201312031319146_PropertyValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
