using System.Runtime.Serialization;

namespace Shipstation.FulfillmentModule.Web.Models.Order
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://example.com/XMLSchema/1.0", IsNullable = false)]
    public partial class Orders
    {

        private OrdersOrder[] orderField;

        private short pagesField;

        private bool pagesFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Order")]
        public OrdersOrder[] Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short pages
        {
            get
            {
                return this.pagesField;
            }
            set
            {
                this.pagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagesSpecified
        {
            get
            {
                return this.pagesFieldSpecified;
            }
            set
            {
                this.pagesFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrder
    {

        private string orderIDField;

        private string orderNumberField;

        private string orderDateField;

        private string orderStatusField;

        private string lastModifiedField;

        private string shippingMethodField;

        private string paymentMethodField;

        private float orderTotalField;

        private float taxAmountField;

        private bool taxAmountFieldSpecified;

        private float shippingAmountField;

        private bool shippingAmountFieldSpecified;

        private string customerNotesField;

        private string internalNotesField;

        private bool giftField;

        private bool giftFieldSpecified;

        private string giftMessageField;

        private string customField1Field;

        private string customField2Field;

        private string customField3Field;

        private OrdersOrderCustomer customerField;

        private OrdersOrderItem[] itemsField;

        [XmlElement("OrderID")]
        public System.Xml.XmlCDataSection OrderIDCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(OrderID);
            }
            set
            {
                OrderID = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        [XmlElement("OrderNumber")]
        public System.Xml.XmlCDataSection OrderNumberCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(OrderNumber);
            }
            set
            {
                OrderNumber = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        public string OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        [XmlElement("OrderStatus", IsNullable = true)]
        public System.Xml.XmlCDataSection OrderStatusCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(OrderStatus);
            }
            set
            {
                OrderStatus = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string OrderStatus
        {
            get
            {
                return this.orderStatusField;
            }
            set
            {
                this.orderStatusField = value;
            }
        }

        /// <remarks/>
        public string LastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }

        [XmlElement("ShippingMethod", IsNullable = true)]
        public System.Xml.XmlCDataSection ShippingMethodCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(ShippingMethod);
            }
            set
            {
                ShippingMethod = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string ShippingMethod
        {
            get
            {
                return this.shippingMethodField;
            }
            set
            {
                this.shippingMethodField = value;
            }
        }

        [XmlElement("PaymentMethod", IsNullable = false)]
        public System.Xml.XmlCDataSection PaymentMethodCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(PaymentMethod);
            }
            set
            {
                PaymentMethod = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }

        /// <remarks/>
        public float OrderTotal
        {
            get
            {
                return this.orderTotalField;
            }
            set
            {
                this.orderTotalField = value;
            }
        }

        /// <remarks/>
        public float TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxAmountSpecified
        {
            get
            {
                return this.taxAmountFieldSpecified;
            }
            set
            {
                this.taxAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public float ShippingAmount
        {
            get
            {
                return this.shippingAmountField;
            }
            set
            {
                this.shippingAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingAmountSpecified
        {
            get
            {
                return this.shippingAmountFieldSpecified;
            }
            set
            {
                this.shippingAmountFieldSpecified = value;
            }
        }

        [XmlElement("CustomerNotes", IsNullable = true)]
        public System.Xml.XmlCDataSection CustomerNotesCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(CustomerNotes);
            }
            set
            {
                CustomerNotes = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string CustomerNotes
        {
            get
            {
                return this.customerNotesField;
            }
            set
            {
                this.customerNotesField = value;
            }
        }

        [XmlElement("InternalNotes", IsNullable = true)]
        public System.Xml.XmlCDataSection InternalNotesCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(InternalNotes);
            }
            set
            {
                InternalNotes = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string InternalNotes
        {
            get
            {
                return this.internalNotesField;
            }
            set
            {
                this.internalNotesField = value;
            }
        }

        /// <remarks/>
        public bool Gift
        {
            get
            {
                return this.giftField;
            }
            set
            {
                this.giftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GiftSpecified
        {
            get
            {
                return this.giftFieldSpecified;
            }
            set
            {
                this.giftFieldSpecified = value;
            }
        }

        [XmlElement("GiftMessage", IsNullable = true)]
        public System.Xml.XmlCDataSection GiftMessageCDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(GiftMessage);
            }
            set
            {
                GiftMessage = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string GiftMessage
        {
            get
            {
                return this.giftMessageField;
            }
            set
            {
                this.giftMessageField = value;
            }
        }

        [XmlElement("CustomField1", IsNullable = true)]
        public System.Xml.XmlCDataSection CustomField1CDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(CustomField1);
            }
            set
            {
                CustomField1 = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string CustomField1
        {
            get
            {
                return this.customField1Field;
            }
            set
            {
                this.customField1Field = value;
            }
        }

        [XmlElement("CustomField2")]
        public System.Xml.XmlCDataSection CustomField2CDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(CustomField2);
            }
            set
            {
                CustomField2 = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string CustomField2
        {
            get
            {
                return this.customField2Field;
            }
            set
            {
                this.customField2Field = value;
            }
        }

        [XmlElement("CustomField3")]
        public System.Xml.XmlCDataSection CustomField3CDATA
        {
            get
            {
                return new System.Xml.XmlDocument().CreateCDataSection(CustomField3);
            }
            set
            {
                CustomField3 = value.Value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public string CustomField3
        {
            get
            {
                return this.customField3Field;
            }
            set
            {
                this.customField3Field = value;
            }
        }

        /// <remarks/>
        public OrdersOrderCustomer Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public OrdersOrderItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrderCustomer
    {

        private string customerCodeField;

        private OrdersOrderCustomerBillTo billToField;

        private OrdersOrderCustomerShipTo shipToField;

        /// <remarks/>
        public string CustomerCode
        {
            get
            {
                return this.customerCodeField;
            }
            set
            {
                this.customerCodeField = value;
            }
        }

        /// <remarks/>
        public OrdersOrderCustomerBillTo BillTo
        {
            get
            {
                return this.billToField;
            }
            set
            {
                this.billToField = value;
            }
        }

        /// <remarks/>
        public OrdersOrderCustomerShipTo ShipTo
        {
            get
            {
                return this.shipToField;
            }
            set
            {
                this.shipToField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrderCustomerBillTo
    {

        private string nameField;

        private string companyField;

        private string phoneField;

        private string emailField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrderCustomerShipTo
    {

        private string nameField;

        private string companyField;

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string stateField;

        private string postalCodeField;

        private string countryField;

        private string phoneField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrderItem
    {

        private string lineItemIDField;

        private string sKUField;

        private string nameField;

        private bool adjustmentField;

        private bool adjustmentFieldSpecified;

        private string imageUrlField;

        private float weightField;

        private bool weightFieldSpecified;

        private string weightUnitsField;

        private sbyte quantityField;

        private float unitPriceField;

        private string locationField;

        private OrdersOrderItemOption[] optionsField;

        /// <remarks/>
        public string LineItemID
        {
            get
            {
                return this.lineItemIDField;
            }
            set
            {
                this.lineItemIDField = value;
            }
        }

        /// <remarks/>
        public string SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public bool Adjustment
        {
            get
            {
                return this.adjustmentField;
            }
            set
            {
                this.adjustmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjustmentSpecified
        {
            get
            {
                return this.adjustmentFieldSpecified;
            }
            set
            {
                this.adjustmentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }

        /// <remarks/>
        public float Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified
        {
            get
            {
                return this.weightFieldSpecified;
            }
            set
            {
                this.weightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string WeightUnits
        {
            get
            {
                return this.weightUnitsField;
            }
            set
            {
                this.weightUnitsField = value;
            }
        }

        /// <remarks/>
        public sbyte Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public float UnitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }

        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Option", IsNullable = false)]
        public OrdersOrderItemOption[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/XMLSchema/1.0")]
    public partial class OrdersOrderItemOption
    {

        private string nameField;

        private string valueField;

        private float weightField;

        private bool weightFieldSpecified;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public float Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified
        {
            get
            {
                return this.weightFieldSpecified;
            }
            set
            {
                this.weightFieldSpecified = value;
            }
        }
    }

    public enum OrderStatusEnum
    {
        [EnumMember(Value = "AwaitingPayment")]
        AwaitingPayment = 1,
        [EnumMember(Value = "AwaitingShipment")]
        AwaitingShipment = 2,
        [EnumMember(Value = "Shipped")]
        Shipped = 3,
        [EnumMember(Value = "Cancelled")]
        Cancelled = 4,
        [EnumMember(Value = "OnHold")]
        OnHold = 5
    }
}