// <auto-generated />
namespace VirtoCommerce.PricingModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DropDescriminator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropDescriminator));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131253288_DropDescriminator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
