//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.Bootstrapper.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.Bootstrapper.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically exit for non-interactive mode.
        /// </summary>
        public static string AutomaticallyExitForNonInteractiveMode {
            get {
                return ResourceManager.GetString("AutomaticallyExitForNonInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been cancelled..
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel?.
        /// </summary>
        public static string ConfirmCancellation {
            get {
                return ResourceManager.GetString("ConfirmCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of VirtoCommerce is already installed..
        /// </summary>
        public static string Downgrade {
            get {
                return ResourceManager.GetString("Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Virto Commerce SDK setup files to:.
        /// </summary>
        public static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virto Commerce Search.
        /// </summary>
        public static string ElasticSearch {
            get {
                return ResourceManager.GetString("ElasticSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Store web app project to:.
        /// </summary>
        public static string ExtractTo {
            get {
                return ResourceManager.GetString("ExtractTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the License terms.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string InstallationTitle {
            get {
                return ResourceManager.GetString("InstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features to install.
        /// </summary>
        public static string InstallFeatures {
            get {
                return ResourceManager.GetString("InstallFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Virto Commerce to:.
        /// </summary>
        public static string InstallTo {
            get {
                return ResourceManager.GetString("InstallTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking automatic plan for non-interactive mode..
        /// </summary>
        public static string InvokingAutomaticPlanForNonInteractiveMode {
            get {
                return ResourceManager.GetString("InvokingAutomaticPlanForNonInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking automatic plan for uninstall.
        /// </summary>
        public static string InvokingAutomaticPlanForUninstall {
            get {
                return ResourceManager.GetString("InvokingAutomaticPlanForUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch configuration wizard.
        /// </summary>
        public static string LaunchConfiguration {
            get {
                return ResourceManager.GetString("LaunchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LayoutTitle {
            get {
                return ResourceManager.GetString("LayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License terms.
        /// </summary>
        public static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  before you can install the product..
        /// </summary>
        public static string LicenseTextAfterLink {
            get {
                return ResourceManager.GetString("LicenseTextAfterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the .
        /// </summary>
        public static string LicenseTextBeforeLink {
            get {
                return ResourceManager.GetString("LicenseTextBeforeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LinkHere {
            get {
                return ResourceManager.GetString("LinkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string ModificationTitle {
            get {
                return ResourceManager.GetString("ModificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation progress:.
        /// </summary>
        public static string OperationProgress {
            get {
                return ResourceManager.GetString("OperationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virto Commerce.
        /// </summary>
        public static string SDKTitle {
            get {
                return ResourceManager.GetString("SDKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfully completed..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prerequisites have been installed, proceed with a configuration utility to finish setting up an SDK..
        /// </summary>
        public static string SuccessfulInstall {
            get {
                return ResourceManager.GetString("SuccessfulInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search have been installed successfully..
        /// </summary>
        public static string SuccessfulSearchInstall {
            get {
                return ResourceManager.GetString("SuccessfulSearchInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to review the JRE installation log file (if exists),.
        /// </summary>
        public static string TextAfterJRELogLink {
            get {
                return ResourceManager.GetString("TextAfterJRELogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to review the SDK installation log file,.
        /// </summary>
        public static string TextAfterSDKLogLink {
            get {
                return ResourceManager.GetString("TextAfterSDKLogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to review the Elastic search installation log file (if exists)..
        /// </summary>
        public static string TextAfterSearchLogLink {
            get {
                return ResourceManager.GetString("TextAfterSearchLogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to see the common issues and workarounds, .
        /// </summary>
        public static string TextAfterTroubleshootLink {
            get {
                return ResourceManager.GetString("TextAfterTroubleshootLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to review the VirtoCommerce installation log file,.
        /// </summary>
        public static string TextAfterVirtoCommerceLogLink {
            get {
                return ResourceManager.GetString("TextAfterVirtoCommerceLogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the following warnings. Click.
        /// </summary>
        public static string TextBeforeTroubleshootLink {
            get {
                return ResourceManager.GetString("TextBeforeTroubleshootLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virto Commerce SDK.
        /// </summary>
        public static string VirtoCommerceSDK {
            get {
                return ResourceManager.GetString("VirtoCommerceSDK", resourceCulture);
            }
        }
    }
}
