// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Catalogs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class EditorialReviewLocale_SeoTriggers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditorialReviewLocale_SeoTriggers));
        
        string IMigrationMetadata.Id
        {
            get { return "201409031214424_EditorialReviewLocale_SeoTriggers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
