// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Catalogs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class СatalogProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(СatalogProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201502160901190_СatalogProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
