//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPerfTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class CatalogBrowseCoded : WebTest
    {
        private string Url = String.Empty;

        public CatalogBrowseCoded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            var url = this.Context["Website"];
            Url = url != null ? url.ToString() : Url;

            if (String.IsNullOrEmpty(Url))
            {
                throw new ArgumentNullException("Make sure to set Url context variable");
            }

            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest(Url);
            request1.ParseDependentRequests = false;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest(Url + "/videoandvideo");
            request2.ParseDependentRequests = false;
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest(Url + "/audio");
            request3.ParseDependentRequests = false;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest(Url + "/cameras");
            request4.ParseDependentRequests = false;
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest(Url + "/computers");
            request5.ParseDependentRequests = false;
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest(Url + "/accessories");
            request6.ParseDependentRequests = false;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest(Url + "/accessories");
            request7.ParseDependentRequests = false;
            request7.QueryStringParameters.Add("f_Brand", "sony", false, false);
            request7.QueryStringParameters.Add("p", "1", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest(Url + "/videoandvideo");
            request8.ParseDependentRequests = false;
            request8.QueryStringParameters.Add("p", "4", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest(Url + "/videoandvideo/televisions/sony-bravia-bx-300-series-32-inch-lcd-tv-black");
            request9.ParseDependentRequests = false;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest(Url + "/videoandvideo/televisions/sony-bravia-klv-32ex400-32-1080p-full-hd-multi-system-palntscsecam-lcd-tv-dual-110-220-voltage-f-116");
            request10.ParseDependentRequests = false;
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest(Url + "/videoandvideo");
            request11.ParseDependentRequests = false;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest(Url + "/cameras/sony-cyber-shot-dsc-wx9-162-mp-exmor-r-cmos-digital-still-camera-with-carl-zeiss-vario-tessar-5x-w-160");
            request12.ParseDependentRequests = false;
            yield return request12;
            request12 = null;
        }
    }
}
