// <auto-generated />
namespace VirtoCommerce.Foundation.Data.AppConfig.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class UpdateStatisticsProceduresAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateStatisticsProceduresAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201407291500445_UpdateStatisticsProceduresAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
