//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.ManagementClient.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.ManagementClient.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account details.
        /// </summary>
        public static string Account_details {
            get {
                return ResourceManager.GetString("Account_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base url.
        /// </summary>
        public static string Baseurl {
            get {
                return ResourceManager.GetString("Baseurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string Create_role {
            get {
                return ResourceManager.GetString("Create_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to change password: {0}.
        /// </summary>
        public static string error_occurred_when_trying_to_change_password {
            get {
                return ResourceManager.GetString("error_occurred_when_trying_to_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to load Permissions for: {0}.
        /// </summary>
        public static string error_occurred_when_trying_to_load_Permissions {
            get {
                return ResourceManager.GetString("error_occurred_when_trying_to_load_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to reset password: {0}.
        /// </summary>
        public static string error_occurred_when_trying_to_reset {
            get {
                return ResourceManager.GetString("error_occurred_when_trying_to_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is incorrect.
        /// </summary>
        public static string errorLogin_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("errorLogin_or_password_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string groupCatalog {
            get {
                return ResourceManager.GetString("groupCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string groupCustomer_Service {
            get {
                return ResourceManager.GetString("groupCustomer_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment.
        /// </summary>
        public static string groupFulfillment {
            get {
                return ResourceManager.GetString("groupFulfillment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string groupMarketing {
            get {
                return ResourceManager.GetString("groupMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string groupOrders {
            get {
                return ResourceManager.GetString("groupOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string groupPricing {
            get {
                return ResourceManager.GetString("groupPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string groupSettings {
            get {
                return ResourceManager.GetString("groupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopper.
        /// </summary>
        public static string groupShopper {
            get {
                return ResourceManager.GetString("groupShopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string groupUsers {
            get {
                return ResourceManager.GetString("groupUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest User.
        /// </summary>
        public static string Guest_User {
            get {
                return ResourceManager.GetString("Guest_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string loginAct {
            get {
                return ResourceManager.GetString("loginAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        public static string Pending_Approval {
            get {
                return ResourceManager.GetString("Pending_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qw.
        /// </summary>
        public static string qw {
            get {
                return ResourceManager.GetString("qw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered User.
        /// </summary>
        public static string Registered_User {
            get {
                return ResourceManager.GetString("Registered_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Role_Name_plain {
            get {
                return ResourceManager.GetString("Role_Name_plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Roles.
        /// </summary>
        public static string Set_Roles {
            get {
                return ResourceManager.GetString("Set_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administrator.
        /// </summary>
        public static string Site_Administrator {
            get {
                return ResourceManager.GetString("Site_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string TextBlock_Text {
            get {
                return ResourceManager.GetString("TextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER MANAGEMENT.
        /// </summary>
        public static string USER_MANAGEMENT {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Role information..
        /// </summary>
        public static string wiz_Role_information {
            get {
                return ResourceManager.GetString("wiz_Role_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User general information..
        /// </summary>
        public static string wiz_User_general_information {
            get {
                return ResourceManager.GetString("wiz_User_general_information", resourceCulture);
            }
        }
    }
}
