// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201307241053334_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
