// <auto-generated />
namespace VirtoCommerce.Foundation.Data.AppConfig.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Seo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seo));
        
        string IMigrationMetadata.Id
        {
            get { return "201401130952595_Seo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
