// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Orders.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ShipmentOptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShipmentOptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241106023_ShipmentOptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
