// <auto-generated />
namespace VirtoCommerce.CoreModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class LanguageOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LanguageOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201604080904338_LanguageOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
