// <auto-generated />
namespace VirtoCommerce.CartModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DimensionChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DimensionChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201506011123083_DimensionChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
