// <auto-generated />
namespace VirtoCommerce.CustomerModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class VendorAndEmployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VendorAndEmployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201603291317073_VendorAndEmployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
