// <auto-generated />
namespace VirtoCommerce.StoreModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TaxProviders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaxProviders));
        
        string IMigrationMetadata.Id
        {
            get { return "201509151255225_TaxProviders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
