// <auto-generated />
namespace VirtoCommerce.Content.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AssociatedObjectNameField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssociatedObjectNameField));
        
        string IMigrationMetadata.Id
        {
            get { return "201602150959294_AssociatedObjectNameField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
