// <auto-generated />
namespace VirtoCommerce.CatalogModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ItemCodeUniqueConstrain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemCodeUniqueConstrain));
        
        string IMigrationMetadata.Id
        {
            get { return "201505130951362_ItemCodeUniqueConstrain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
