// <auto-generated />
namespace VirtoCommerce.CatalogModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AssetChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssetChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201506291457346_AssetChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
