//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.FrontEnd.FunctionalTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.FrontEnd.FunctionalTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LambdaExpression NodeType=&quot;Lambda&quot; Name=&quot;&quot; TailCall=&quot;false&quot; CanReduce=&quot;false&quot;&gt;
        ///  &lt;Type&gt;
        ///    &lt;Type Name=&quot;System.Func`2&quot;&gt;
        ///      &lt;Type Name=&quot;VirtoCommerce.Foundation.Frameworks.IEvaluationContext&quot; /&gt;
        ///      &lt;Type Name=&quot;System.Boolean&quot; /&gt;
        ///    &lt;/Type&gt;
        ///  &lt;/Type&gt;
        ///  &lt;Parameters&gt;
        ///    &lt;ParameterExpression NodeType=&quot;Parameter&quot; Name=&quot;f&quot; IsByRef=&quot;false&quot; CanReduce=&quot;false&quot;&gt;
        ///      &lt;Type&gt;
        ///        &lt;Type Name=&quot;VirtoCommerce.Foundation.Frameworks.IEvaluationContext&quot; /&gt;
        ///      &lt;/Type&gt;
        ///    &lt;/ParameterExpression&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromotionExpression_Item0 {
            get {
                return ResourceManager.GetString("PromotionExpression_Item0", resourceCulture);
            }
        }
    }
}
