//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.ManagementClient.AppConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.ManagementClient.AppConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is .
        /// </summary>
        public static string Category_is {
            get {
                return ResourceManager.GetString("Category_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is [].
        /// </summary>
        public static string Category_is_ {
            get {
                return ResourceManager.GetString("Category_is_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is subcategory of .
        /// </summary>
        public static string Category_is_subcategory_of_ {
            get {
                return ResourceManager.GetString("Category_is_subcategory_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is subcategory of [].
        /// </summary>
        public static string Category_is_subcategory_of__ {
            get {
                return ResourceManager.GetString("Category_is_subcategory_of__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category property is [] .
        /// </summary>
        public static string Category_property_is__ {
            get {
                return ResourceManager.GetString("Category_property_is__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias:.
        /// </summary>
        public static string Parameter_Alias {
            get {
                return ResourceManager.GetString("Parameter_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Parameter_Name {
            get {
                return ResourceManager.GetString("Parameter_Name", resourceCulture);
            }
        }
    }
}
