// <auto-generated />
namespace VirtoCommerce.QuoteModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ExtraFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtraFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201509161439413_ExtraFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
