//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.ManagementClient.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Click to go to Customer service.
		/// </summary>
		public static string Click_to_go_to_Customer_service
		{
			get
			{
				return ResourceManager.GetString("Click_to_go_to_Customer_service", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Click to go to Dashboard.
		/// </summary>
		public static string Click_to_go_to_Dashboard
		{
			get
			{
				return ResourceManager.GetString("Click_to_go_to_Dashboard", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connected to: {0}.
		/// </summary>
		public static string Connected_to_
		{
			get
			{
				return ResourceManager.GetString("Connected_to_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Show main menu.
		/// </summary>
		public static string Show_main_menu
		{
			get
			{
				return ResourceManager.GetString("Show_main_menu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Version: {0} (Build {1}).
		/// </summary>
		public static string Version_0___Build__1__
		{
			get
			{
				return ResourceManager.GetString("Version_0___Build__1__", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon VirtoCommerce
		{
			get
			{
				object obj = ResourceManager.GetObject("VirtoCommerce", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
	}
}
