//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.OrderModule.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderNotificationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderNotificationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.OrderModule.Web.Resources.OrderNotificationResource", typeof(OrderNotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order &lt;strong&gt;{{ ordernumber }}&lt;/strong&gt;.&lt;br&gt; Cancelation order reason - &lt;strong&gt;{{ cancelationreason }}&lt;/strong&gt;..
        /// </summary>
        public static string CancelOrderNotificationBody {
            get {
                return ResourceManager.GetString("CancelOrderNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was canceled.
        /// </summary>
        public static string CancelOrderNotificationSubject {
            get {
                return ResourceManager.GetString("CancelOrderNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order number  - &lt;strong&gt;{{ ordernumber }}&lt;/strong&gt;..
        /// </summary>
        public static string CreateOrderNotificationBody {
            get {
                return ResourceManager.GetString("CreateOrderNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order created.
        /// </summary>
        public static string CreateOrderNotificationSubject {
            get {
                return ResourceManager.GetString("CreateOrderNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order &lt;strong&gt;{{ ordernumber }}&lt;/strong&gt; change status from &lt;strong&gt;{{ oldstatus }}&lt;strong&gt; to &lt;strong&gt;{{ newstatus }}&lt;strong&gt;..
        /// </summary>
        public static string NewOrderStatusNotificationBody {
            get {
                return ResourceManager.GetString("NewOrderStatusNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order status has been change.
        /// </summary>
        public static string NewOrderStatusNotificatonSubject {
            get {
                return ResourceManager.GetString("NewOrderStatusNotificatonSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for paying &lt;strong&gt;{{ ordernumber }}&lt;/strong&gt; order.&lt;br&gt; You had paid &lt;strong&gt;{{ fullprice }} {{ currency }}&lt;/strong&gt;.&lt;br&gt; Paid date - &lt;strong&gt;{{ paiddate }}&lt;/strong&gt;..
        /// </summary>
        public static string OrderPaidNotificationBody {
            get {
                return ResourceManager.GetString("OrderPaidNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was fully paid.
        /// </summary>
        public static string OrderPaidNotificationSubject {
            get {
                return ResourceManager.GetString("OrderPaidNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order &lt;strong&gt;{{ ordernumber }}&lt;/strong&gt; was sent.&lt;br&gt; Number of sent parcels - &lt;strong&gt;{{ numberofshipments }}&lt;/strong&gt;.&lt;br&gt; Parcels tracking numbers:&lt;br&gt; {% for shipmentnumber in shipmentsnumbers %} &lt;br&gt;&lt;strong&gt;{{ shipmentnumber }}&lt;/strong&gt; {% endfor %}&lt;br&gt;&lt;br&gt;Sent date - &lt;strong&gt;{{ sentorderdate }}&lt;/strong&gt;..
        /// </summary>
        public static string OrderSentNotificationBody {
            get {
                return ResourceManager.GetString("OrderSentNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was sent.
        /// </summary>
        public static string OrderSentNotificationSubject {
            get {
                return ResourceManager.GetString("OrderSentNotificationSubject", resourceCulture);
            }
        }
    }
}
