name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   workflow_dispatch:
    inputs:
      versionTag:
        description: 'Image version tag'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deployment pending') }}
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.1.0"

    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Development
        no_override: false

    - name: Commit environment change
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/VirtoCommerce/vc-deploy-apps.git
        cd vc-deploy-apps/webstore-app/overlays/dev

        $REPOSITORY = "docker.pkg.github.com/$('${{ github.repository }}'.ToLower())"
        kustomize edit set image virtocommerce/platform=$REPOSITORY/platform:${{ github.event.inputs.versionTag }}

        git config user.email "github.actions@virtoway.com"
        git config user.name "GitHub Actions"

        git add .
        git commit -m "Update the platform image version to $($version)"

        $remoteRepo="https://${{ github.actor }}:${{ secrets.REPO_TOKEN }}@github.com/VirtoCommerce/vc-deploy-apps.git"

        git push $remoteRepo

    - name: Wait for environment is up
      shell: pwsh
      timeout-minutes: 5
      run: | 
        do {
          Start-Sleep -s 15

          $statusBage = (Invoke-WebRequest -Uri "https://cd.govirto.com/api/badge?name=webstore-dev-app").Content
          
          $syncedAndHealthy = $statusBage.Contains('>Healthy<') -and $statusBage.Contains('>Synced<')

          if (-not $syncedAndHealthy) {
            Write-Host "Sync pending..."
          }
        }
        while (-not $syncedAndHealthy)

    - name: BUILD_STATE::successful
      if: success()
      run: echo "::set-env name=BUILD_STATE::successful"

    - name: BUILD_STATE::failed
      if: failure()
      run: echo "::set-env name=BUILD_STATE::failed"

    - name: Update GitHub deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Parse Jira Keys from All Commits
      id: jira_keys
      if: always()
      uses: HighwayThree/jira-extract-issue-keys@master
      with:
        is-pull-request: ${{ github.event_name == 'pull_request' }}
        parse-all-commits: ${{ github.event_name == 'push' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Push Deployment Info to Jira
      if: ${{ env.CLOUD_INSTANCE_BASE_URL != 0 && env.CLIENT_ID != 0 && env.CLIENT_SECRET != 0 && steps.jira_keys.outputs.jira-keys != '' && always() }}
      id: push_deployment_info_to_jira
      uses: HighwayThree/jira-upload-deployment-info@master
      env:
        CLOUD_INSTANCE_BASE_URL: ${{secrets.CLOUD_INSTANCE_BASE_URL}}
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      with:
        cloud-instance-base-url: '${{ secrets.CLOUD_INSTANCE_BASE_URL }}'
        client-id: '${{ secrets.CLIENT_ID }}'
        client-secret: '${{ secrets.CLIENT_SECRET }}'
        deployment-sequence-number: '${{ github.run_id }}'
        update-sequence-number: '${{ github.run_id }}'
        issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
        display-name: "http://webstore-platform.dev.govirto.com/"
        url: "http://webstore-platform.dev.govirto.com/"
        description: "Deployment to the Development environment"
        last-updated: '${{github.event.head_commit.timestamp}}'
        state: "${{ env.BUILD_STATE }}"
        pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
        pipeline-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
        pipeline-url: '${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}'
        environment-id: 'development'
        environment-display-name: 'Dev'
        environment-type: 'development'

    - name: Remove Deployment Pending Label
      uses: buildsville/add-remove-label@v1
      if: ${{ always() && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deployment pending') }}
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: 'deployment pending'
        type: remove
