# v1.2
name: Platform OWASP ZAP
on:
  # push:
  #   paths-ignore:
  #     - '.github/**'
  #     - 'docs/**'
  #     - 'build/**'
  #     - 'README.md'
  #     - 'LICENSE'
  #     - '**/argoDeploy.json'
  #   branches: [ dev ]
  workflow_dispatch:

jobs:
  owasp:
    runs-on: ubuntu-latest

    steps:

      - name: Install VirtoCommerce.GlobalTool
        uses: VirtoCommerce/vc-github-actions/setup-vcbuild@VCST-5054 #master

      - name: Docker Login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Env
        uses: VirtoCommerce/vc-github-actions/docker-env@VCST-5054 #master
        with:
          githubUser: ${{ env.GITHUB_ACTOR }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          platformImage: ghcr.io/virtocommerce/platform
          storefrontImage: ghcr.io/virtocommerce/storefront
          validateSwagger: 'false'

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 # v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8090'
          cmd_options: '-a -d'
