name: TODO Bot

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: adriangodong/actions-todo-bot@1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
