name: TODO Bot

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') }}  # Check that PR not from forked repo and not from Dependabot

    runs-on: ubuntu-latest

    steps:
    - uses: adriangodong/actions-todo-bot@1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
