# v3.800.35
# https://virtocommerce.atlassian.net/browse/VCST-5063
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.35    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}