// <auto-generated />
namespace VirtoCommerce.Platform.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NotificationAddLanguagesAndObjectType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotificationAddLanguagesAndObjectType));
        
        string IMigrationMetadata.Id
        {
            get { return "201506301244090_NotificationAddLanguagesAndObjectType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
