// <auto-generated />
namespace VirtoCommerce.Platform.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewIndexes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewIndexes2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311021135_NewIndexes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
