// <auto-generated />
namespace VirtoCommerce.Foundation.Data.Marketing.Migrations.Promotion
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedUsageProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedUsageProps));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041337025_AddedUsageProps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
